### ISSUE TITLE
Missing - Resolution to the affected libraries

### ISSUE THREAD

**Issue by RWavdhane** [whitesource-ps/ws-top10-rejected-libs#10]
Hello Team,

The generated report lists the affected library but does not have the fixing (mitigation) information in it. Although, there is a link to library details page from WhiteSource, but it would be very handy and quick to fix the alerts if the resolution (top fix(es)) are included in reports.

Thanks!
Rahul

**Comment by NatalyaDalid** [comment]
Hello Rahul,

This feature is not in the scope of this open-source project but can be developed for you in the scope of the customized project.

Thank you,
WhiteSource PS team
