### ISSUE TITLE
Consolidated information about all the affected versions of a library

### ISSUE THREAD

**Issue by RWavdhane** [whitesource-ps/ws-top10-rejected-libs#11]
Hello Team,

Generated report has only the version specific library data. We need to circulate this list to everyone in the organization. Due to the version specific alerts mentioned in report, it becomes partial data that we are rolling out to the general product teams. The teams using other affected versions would not be notified about their versions status. We would really like to see the consolidated data for all the affected versions of a particular library.

**P.S.:** WhiteSource scan results are regularly being inspected and verified by the experts.

For example: Report highlights that 58 projects are affected by library "pqr" with version 1.1.1. But other versions of library "pqr" used by other product teams are not highlighted. This will install the relief in those remaining product teams that though their version of "pqr" library is affected they do not have to worry as it is not listed in the list. The ask here is to have a consolidated data of all the affected versions of library "pqr" so every team using it would be notified and would take the corrective actions.

Thanks!
Rahul

**Comment by NatalyaDalid** [comment]
Hello Rahul,

This feature is not in the scope of this open-source project but can be developed for you in the scope of the customized project.

Thank you,
WhiteSource PS team
