### ISSUE TITLE
Missing - CVE IDs of affected Libraries

### ISSUE THREAD

**Issue by RWavdhane** [whitesource-ps/ws-top10-rejected-libs#9]
Hello Team,

Final generated report does not contain CVE ID information for affected libraries. It would be very useful to have the CVE IDs for the affected libraries in the final report. This will allow the Security Subject Matter Experts to analyze the CVE of the library and advice the teams on whether the alert really affects the used functionality of the open source code or not. 

Thanks!
Rahul

**Comment by NatalyaDalid** [comment]
Hello Rahul,

This feature is not in the scope of this open-source project but can be developed for you in the scope of the customized project.

Thank you,
WhiteSource PS team
